defaults:
  - model: lstm

verbose: 100
seed: 42

cudnn:
  benchmark: true
  deterministic: false

##################################################
#               DATA SETTING                     #
##################################################
data:
  train:
    utt_list: ../data/train.list
    in_dir: ../data/dump/jsut_sr16000/org/train/in_dulation
    out_dir: ../data/dump/jsut_sr16000/org/train/out_dulation

  dev:
    utt_list: ../data/dev.list
    in_dir: ../data/dump/jsut_sr16000/org/dev/in_dulation
    out_dir: ../data/dump/jsut_sr16000/org/dev/out_dulation

  # dataloader
  num_workers: 4
  batch_size: 256

##################################################
#               TRAIN SETTING                    #
##################################################
train:
  out_dir: exp
  log_dir: exp/log

  epochs: 30
  checkpoint_epoch_interval: 10

  optim:
    optimizer:
      name: Adam
      params:
        lr: 1e-4
        betas: [0.9, 0.999]
        weight_decay: 0.0
    lr_scheduler:
      name: StepLR
      params:
        step_size: 10
        gamma: 0.5